name: SIIM_BIP
dependencies:
  - python=3.6
  - numpy
  - pandas
  - seaborn
  - scikit-learn
  - pip:
    - ipympl
    - jupyterlab
    - pydicom
    - "--editable=git+https://github.com/SimpleITK/SimpleITK@latest#egg=SimpleITK"
    - itk
    - itkwidgets
    - itk-elastix
