name: SIIM_BIP
dependencies:
  - python=3.9
  - numpy
  - pandas
  - seaborn
  - scikit-learn
  - pip:
    - ipympl
    - pydicom
    - SimpleITK
    - itk
    - itk-elastix
    - jupyterlab
    - notebook        
    - napari[all]
    - deid