name: SIIM_BIP
dependencies:
  - python=3.6
  - numpy
  - pandas
  - seaborn
  - scikit-learn
  - git
  - pip
  - pip:
    - ipympl
    - jupyterlab
    - pydicom
    - "git+git://github.com/SimpleITK/SimpleITK@master#egg=SimpleITK"
    - itk
    - itkwidgets
    - itk-elastix
